import { Spot, User } from './types';
const generateForecast = (baseSpeed: number): any[] => {
  return Array.from({ length: 24 }).map((_, i) => ({
    time: `${i}:00`,
    windSpeed: baseSpeed + Math.sin(i / 3) * 5 + Math.random() * 2,
    gust: baseSpeed + 8 + Math.sin(i / 3) * 5 + Math.random() * 4,
    direction: 310 + Math.random() * 20,
  }));
};
export const MOCK_SPOTS: Spot[] = [
  {
    id: 'prasonisi-rhodes',
    name: 'Prasonisi',
    location: 'Rhodes, Greece',
    region: 'Dodecanese',
    image: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&q=80&w=800',
    description: 'The world-famous meeting point of two seas. Flat water on one side, waves on the other.',
    generalRating: 9.5,
    sportRatings: { windsurf: 10, kite: 9, wing: 8, surf: 4 },
    forecast: generateForecast(22),
    aiInsight: {
      summary: "Meltemi is pumping. Solid 22-28 knots expected from noon. Perfect for smaller sails.",
      idealSport: "Windsurf",
      timeframe: "12:00 - 19:00",
      confidence: 0.95
    },
    lat: 35.92,
    lng: 27.79,
    bestDirection: "NE Meltemi",
    difficulty: 'Expert',
    facilities: ['Pro Center', 'Rescue', 'Parking', 'Taverna', 'Shower'],
    crowd: 'Crowded',
    tips: ['Watch out for the offshore wind on the flat side', 'Rig 4.2-5.0m for the afternoon blast'],
    launchArea: 'Wide sandy spit between two bays. Plenty of rigging space.',
    bestGear: [{ sport: 'windsurf', sizeRange: '4.0-5.3m' }, { sport: 'kite', sizeRange: '7-9m' }],
    schoolInfo: [{ name: 'Prasonisi Center', distanceKm: 0.1, phone: '+30 2244 091045' }]
  },
  {
    id: 'golden-beach-paros',
    name: 'Golden Beach',
    location: 'Paros, Greece',
    region: 'Cyclades',
    image: 'https://images.unsplash.com/photo-1544551763-47a0159f9234?auto=format&fit=crop&q=80&w=800',
    description: 'Crystal clear waters and consistent side-shore winds.',
    generalRating: 8.8,
    sportRatings: { windsurf: 9, kite: 7, wing: 9, surf: 2 },
    forecast: generateForecast(18),
    aiInsight: {
      summary: "Steady thermal breeze building up. Ideal for wingfoiling progression in the bay.",
      idealSport: "Wingfoil",
      timeframe: "14:00 - 18:30",
      confidence: 0.88
    },
    lat: 37.01,
    lng: 25.24,
    bestDirection: "N Thermal",
    difficulty: 'Intermediate',
    facilities: ['Surf Club', 'Beach Bar', 'Parking', 'Sunbeds'],
    crowd: 'High',
    tips: ['Best wind is further out from the shore', 'Morning is great for beginners'],
    launchArea: 'Sandy beach with easy entry.',
    bestGear: [{ sport: 'wing', sizeRange: '4.5-5.5m' }, { sport: 'windsurf', sizeRange: '5.5-7.0m' }],
    schoolInfo: [{ name: 'Sunwind Surf Club', distanceKm: 0.1 }]
  },
  {
    id: 'vassiliki-lefkada',
    name: 'Vassiliki',
    location: 'Lefkada, Greece',
    region: 'Ionian',
    image: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&q=80&w=800',
    description: 'Famous for Eric, the strong cross-shore wind that kicks in every afternoon.',
    generalRating: 9.2,
    sportRatings: { windsurf: 10, kite: 4, wing: 8, surf: 1 },
    forecast: generateForecast(20),
    aiInsight: {
      summary: "Thermal pressure looks good. Expect the cross-shore blast to start around 15:30.",
      idealSport: "Windsurf",
      timeframe: "15:30 - 20:00",
      confidence: 0.92
    },
    lat: 38.62,
    lng: 20.60,
    bestDirection: "SW Eric",
    difficulty: 'Advanced',
    facilities: ['Schools', 'Rescue Boats', 'Hotels', 'Rigging Lawns'],
    crowd: 'High',
    tips: ['Wait for the mountain clouds to form', 'Flat water on the upwind side'],
    launchArea: 'Gravel/grass launch spots along the bay front.',
    bestGear: [{ sport: 'windsurf', sizeRange: '4.7-5.8m' }],
    schoolInfo: [{ name: 'Club Vass', distanceKm: 0.1 }]
  },
  {
    id: 'mikri-vigla-naxos',
    name: 'Mikri Vigla',
    location: 'Naxos, Greece',
    region: 'Cyclades',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    description: 'The kiteboarding capital of the Cyclades. Constant Meltemi through a natural wind tunnel.',
    generalRating: 9.4,
    sportRatings: { windsurf: 8, kite: 10, wing: 9, surf: 2 },
    forecast: generateForecast(21),
    aiInsight: {
      summary: "Tunnel effect is active. Expect 2-3 knots more than the open sea forecast.",
      idealSport: "Kitesurf",
      timeframe: "11:00 - 19:00",
      confidence: 0.94
    },
    lat: 37.02,
    lng: 25.37,
    bestDirection: "N Meltemi",
    difficulty: 'Intermediate',
    facilities: ['Kite Centers', 'Tavernas', 'Parking'],
    crowd: 'High',
    tips: ['Launch area can be tight during peak season'],
    launchArea: 'Sandy bay with side-onshore wind.',
    bestGear: [{ sport: 'kite', sizeRange: '8-10m' }],
    schoolInfo: [{ name: 'Naxos Kite Life', distanceKm: 0.2 }]
  },
  {
    id: 'keros-limnos',
    name: 'Keros Beach',
    location: 'Limnos, Greece',
    region: 'North Aegean',
    image: 'https://images.unsplash.com/photo-1534120247760-c44c3e4a62f1?auto=format&fit=crop&q=80&w=800',
    description: 'A vast bay with super shallow turquoise water. Safe and perfect for progression.',
    generalRating: 9.1,
    sportRatings: { windsurf: 8, kite: 10, wing: 10, surf: 3 },
    forecast: generateForecast(19),
    aiInsight: {
      summary: "Endless flat water runs today. Great for freestyle or learning to foil.",
      idealSport: "Wingfoil",
      timeframe: "10:00 - 18:00",
      confidence: 0.92
    },
    lat: 39.91,
    lng: 25.36,
    bestDirection: "NE Meltemi",
    difficulty: 'Beginner',
    facilities: ['Glamping', 'Schools', 'Rescue', 'Eco-hub'],
    crowd: 'Medium',
    tips: ['Shallow water extends for 150m'],
    launchArea: 'Massive sandy beach.',
    bestGear: [{ sport: 'wing', sizeRange: '5.0m' }, { sport: 'kite', sizeRange: '10-12m' }],
    schoolInfo: [{ name: 'Surf Club Keros', distanceKm: 0.1 }]
  },
  {
    id: 'mastichari-kos',
    name: 'Mastichari',
    location: 'Kos, Greece',
    region: 'Dodecanese',
    image: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?auto=format&fit=crop&q=80&w=800',
    description: 'North-facing beach catching the full force of the Aegean wind with nice rolling swell.',
    generalRating: 8.5,
    sportRatings: { windsurf: 8, kite: 9, wing: 8, surf: 4 },
    forecast: generateForecast(17),
    aiInsight: {
      summary: "Side-onshore conditions providing safe bumps for jumping.",
      idealSport: "Kitesurf",
      timeframe: "13:00 - 18:30",
      confidence: 0.85
    },
    lat: 36.85,
    lng: 27.08,
    bestDirection: "NW Meltemi",
    difficulty: 'Intermediate',
    facilities: ['Centers', 'Showers', 'Hotels'],
    crowd: 'Medium',
    tips: ['Great spot for sunset sessions'],
    launchArea: 'Wide sandy beach.',
    bestGear: [{ sport: 'kite', sizeRange: '9-12m' }],
    schoolInfo: [{ name: 'Horizon Surfing', distanceKm: 0.3 }]
  },
  {
    id: 'elafonisi-crete',
    name: 'Elafonisi',
    location: 'Crete, Greece',
    region: 'Crete',
    image: 'https://images.unsplash.com/photo-1515238152791-8216bfdf89a7?auto=format&fit=crop&q=80&w=800',
    description: 'Pink sand and shallow lagoons. A visual paradise with strong consistent winds.',
    generalRating: 9.3,
    sportRatings: { windsurf: 7, kite: 10, wing: 8, surf: 2 },
    forecast: generateForecast(23),
    aiInsight: {
      summary: "Strong Meltemi meeting the Libyan sea. Lagoon is flat, outside is choppy.",
      idealSport: "Kitesurf",
      timeframe: "10:00 - 17:00",
      confidence: 0.96
    },
    lat: 35.27,
    lng: 23.54,
    bestDirection: "NW Meltemi",
    difficulty: 'Intermediate',
    facilities: ['Parking', 'Snack Bar', 'Basic Rescue'],
    crowd: 'High',
    tips: ['Avoid the swimmer zones near the pink sand'],
    launchArea: 'Lagoon edge or open sea side.',
    bestGear: [{ sport: 'kite', sizeRange: '7-9m' }],
    schoolInfo: [{ name: 'Crete Surf', distanceKm: 1.5 }]
  },
  {
    id: 'mavrovouni-gytheio',
    name: 'Mavrovouni',
    location: 'Peloponnese, Greece',
    region: 'Peloponnese',
    image: 'https://images.unsplash.com/photo-1520116468816-95b69f847357?auto=format&fit=crop&q=80&w=800',
    description: 'Long sandy beach in the Mani peninsula with a very reliable afternoon thermal.',
    generalRating: 8.2,
    sportRatings: { windsurf: 9, kite: 6, wing: 8, surf: 2 },
    forecast: generateForecast(15),
    aiInsight: {
      summary: "Thermal cycle is stable. Expect 15-18 knots from 14:00 onwards.",
      idealSport: "Windsurf",
      timeframe: "14:00 - 19:30",
      confidence: 0.89
    },
    lat: 36.73,
    lng: 22.56,
    bestDirection: "S Thermal",
    difficulty: 'Beginner',
    facilities: ['Camping', 'Schools', 'Tavernas'],
    crowd: 'Low',
    tips: ['Perfect for families and learning'],
    launchArea: '5km of sandy beach.',
    bestGear: [{ sport: 'windsurf', sizeRange: '6.0-7.5m' }],
    schoolInfo: [{ name: 'Ocean Mani', distanceKm: 0.1 }]
  },
  {
    id: 'marmari-euboea',
    name: 'Marmari',
    location: 'Euboea, Greece',
    region: 'Central Greece',
    image: 'https://images.unsplash.com/photo-1544551763-47a0159f9234?auto=format&fit=crop&q=80&w=800',
    description: 'A wind funnel between the mountains and the Petalioi islands.',
    generalRating: 8.7,
    sportRatings: { windsurf: 8, kite: 9, wing: 8, surf: 1 },
    forecast: generateForecast(20),
    aiInsight: {
      summary: "Venturi effect in the strait. Solid pressure all day.",
      idealSport: "Kitesurf",
      timeframe: "09:00 - 18:00",
      confidence: 0.91
    },
    lat: 38.04,
    lng: 24.32,
    bestDirection: "N Meltemi",
    difficulty: 'Advanced',
    facilities: ['Schools', 'Hotels', 'Parking'],
    crowd: 'Medium',
    tips: ['Currents in the strait can be strong'],
    launchArea: 'Sandy spit.',
    bestGear: [{ sport: 'kite', sizeRange: '9m' }],
    schoolInfo: [{ name: 'Kitepark Marmari', distanceKm: 0.1 }]
  },
  {
    id: 'loutsa-ionian',
    name: 'Loutsa (Ionian)',
    location: 'Preveza, Greece',
    region: 'Ionian',
    image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=800',
    description: 'Endless sandy bay on the west coast with clean thermal winds and small waves.',
    generalRating: 8.4,
    sportRatings: { windsurf: 7, kite: 9, wing: 8, surf: 5 },
    forecast: generateForecast(16),
    aiInsight: {
      summary: "Side-onshore thermal breeze building up nicely for a kite session.",
      idealSport: "Kitesurf",
      timeframe: "14:30 - 20:00",
      confidence: 0.87
    },
    lat: 39.19,
    lng: 20.53,
    bestDirection: "NW Thermal",
    difficulty: 'Intermediate',
    facilities: ['Beach Bars', 'Parking', 'Showers'],
    crowd: 'Medium',
    tips: ['Water is deep, watch for shore break'],
    launchArea: 'Kilometers of sand.',
    bestGear: [{ sport: 'kite', sizeRange: '10-12m' }],
    schoolInfo: [{ name: 'Loutsa Surf', distanceKm: 0.5 }]
  },
  {
    id: 'achivadolimni-milos',
    name: 'Achivadolimni',
    location: 'Milos, Greece',
    region: 'Cyclades',
    image: 'https://images.unsplash.com/photo-1520931016436-b999369fe0bf?auto=format&fit=crop&q=80&w=800',
    description: 'A deep bay in Milos that catches the Meltemi, creating perfectly flat water.',
    generalRating: 8.6,
    sportRatings: { windsurf: 9, kite: 7, wing: 8, surf: 1 },
    forecast: generateForecast(19),
    aiInsight: {
      summary: "Flat water heaven. Ideal for speed runs or freestyle windsurf.",
      idealSport: "Windsurf",
      timeframe: "11:00 - 18:00",
      confidence: 0.90
    },
    lat: 36.68,
    lng: 24.44,
    bestDirection: "N Meltemi",
    difficulty: 'Intermediate',
    facilities: ['Camping', 'Parking', 'Taverna'],
    crowd: 'Low',
    tips: ['The wind is gusty near the shore'],
    launchArea: 'Sandy beach inside the bay.',
    bestGear: [{ sport: 'windsurf', sizeRange: '5.0-6.0m' }],
    schoolInfo: [{ name: 'Milos Windsurf', distanceKm: 0.1 }]
  },
  {
    id: 'saint-peter-andros',
    name: 'St. Peter Beach',
    location: 'Andros, Greece',
    region: 'Cyclades',
    image: 'https://images.unsplash.com/photo-1544551763-47a0159f9234?auto=format&fit=crop&q=80&w=800',
    description: 'Consistent Meltemi spot on the west coast of Andros with a relaxed vibe.',
    generalRating: 8.3,
    sportRatings: { windsurf: 8, kite: 7, wing: 9, surf: 2 },
    forecast: generateForecast(18),
    aiInsight: {
      summary: "Steady pressure today. Great for wingfoil progression.",
      idealSport: "Wingfoil",
      timeframe: "12:00 - 18:30",
      confidence: 0.88
    },
    lat: 37.60,
    lng: 24.76,
    bestDirection: "N Meltemi",
    difficulty: 'Intermediate',
    facilities: ['Schools', 'Sunbeds', 'Parking'],
    crowd: 'Medium',
    tips: ['Morning is perfectly flat for foiling'],
    launchArea: 'Large sandy beach.',
    bestGear: [{ sport: 'wing', sizeRange: '4.5-5.5m' }],
    schoolInfo: [{ name: 'Wesurfin Andros', distanceKm: 0.1 }]
  },
  {
    id: 'afiartis-karpathos',
    name: 'Afiartis',
    location: 'Karpathos, Greece',
    region: 'Dodecanese',
    image: 'https://images.unsplash.com/photo-1506466010722-395aa2bef877?auto=format&fit=crop&q=80&w=800',
    description: 'The high-wind capital. Nuclear conditions for the truly addicted.',
    generalRating: 9.8,
    sportRatings: { windsurf: 10, kite: 5, wing: 7, surf: 1 },
    forecast: generateForecast(28),
    aiInsight: {
      summary: "Brutal wind! 30-35 knots expected. Rig your smallest gear.",
      idealSport: "Windsurf",
      timeframe: "09:00 - 20:00",
      confidence: 0.99
    },
    lat: 35.42,
    lng: 27.14,
    bestDirection: "NW Meltemi",
    difficulty: 'Expert',
    facilities: ['Rigging Stations', 'Rescue', 'Studios'],
    crowd: 'Medium',
    tips: ['Booties recommended for the rocky entry'],
    launchArea: 'Small rocky bays with intense offshore wind.',
    bestGear: [{ sport: 'windsurf', sizeRange: '3.4-4.2m' }],
    schoolInfo: [{ name: 'Ion Club Karpathos', distanceKm: 0.1 }]
  },
  {
    id: 'keros-wave-limnos',
    name: 'Keros Wave',
    location: 'Limnos, Greece',
    region: 'North Aegean',
    image: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&q=80&w=800',
    description: 'The wave-side of the famous Keros beach. Clean rollers and cross-shore wind.',
    generalRating: 8.9,
    sportRatings: { windsurf: 8, kite: 9, wing: 8, surf: 8 },
    forecast: generateForecast(20),
    aiInsight: {
      summary: "Swell is picking up. Great cross-shore wave riding conditions.",
      idealSport: "Surf",
      timeframe: "07:00 - 11:00",
      confidence: 0.84
    },
    lat: 39.92,
    lng: 25.38,
    bestDirection: "NE Meltemi",
    difficulty: 'Advanced',
    facilities: ['Eco-Lodge', 'Rescue'],
    crowd: 'Low',
    tips: ['Best waves are at the northern tip'],
    launchArea: 'Sandy beach with shorebreak.',
    bestGear: [{ sport: 'surf', sizeRange: '6\'2"' }],
    schoolInfo: [{ name: 'Surf Club Keros', distanceKm: 0.5 }]
  },
  {
    id: 'loutsa-artemida',
    name: 'Loutsa (Artemida)',
    location: 'Attica, Greece',
    region: 'Attica',
    image: 'https://images.unsplash.com/photo-1500375591448-4a4c84450bd8?auto=format&fit=crop&q=80&w=800',
    description: 'The heart of Athenian watersports. Shallow, safe, and surprisingly consistent.',
    generalRating: 8.2,
    sportRatings: { windsurf: 9, kite: 6, wing: 8, surf: 2 },
    forecast: generateForecast(16),
    aiInsight: {
      summary: "North thermal is steady. Perfect afternoon session for city-dwellers.",
      idealSport: "Windsurf",
      timeframe: "14:00 - 19:00",
      confidence: 0.85
    },
    lat: 37.97,
    lng: 24.01,
    bestDirection: "N Thermal",
    difficulty: 'Beginner',
    facilities: ['Schools', 'Showers', 'Cafes'],
    crowd: 'High',
    tips: ['Watch for swimmers in summer'],
    launchArea: 'Long sandy beach with shallow water.',
    bestGear: [{ sport: 'windsurf', sizeRange: '6.0-7.5m' }],
    schoolInfo: [{ name: 'Athens Watersports', distanceKm: 0.5 }]
  },
  {
    id: 'kalafati-mykonos',
    name: 'Kalafati',
    location: 'Mykonos, Greece',
    region: 'Cyclades',
    image: 'https://images.unsplash.com/photo-1544551763-47a0159f9234?auto=format&fit=crop&q=80&w=800',
    description: 'Professional windsurfing hub in Mykonos. Strong side-shore winds and blue water.',
    generalRating: 8.9,
    sportRatings: { windsurf: 10, kite: 4, wing: 8, surf: 1 },
    forecast: generateForecast(22),
    aiInsight: {
      summary: "Meltemi blast. Side-shore wind is perfect for high-speed runs.",
      idealSport: "Windsurf",
      timeframe: "10:00 - 19:00",
      confidence: 0.93
    },
    lat: 37.44,
    lng: 25.42,
    bestDirection: "N Meltemi",
    difficulty: 'Advanced',
    facilities: ['Pro Centers', 'Hotels', 'Parking'],
    crowd: 'High',
    tips: ['The bay is deep, rescue is mandatory'],
    launchArea: 'Sandy beach.',
    bestGear: [{ sport: 'windsurf', sizeRange: '4.2-5.3m' }],
    schoolInfo: [{ name: 'Pezi Mai', distanceKm: 0.1 }]
  }
];
export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Alex Windrider' }
];